if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

if (!requireNamespace("Seurat", quietly = TRUE))
  install.packages("Seurat")
if (!requireNamespace("argparse", quietly = TRUE))
  install.packages("argparse")
if (!requireNamespace("here", quietly = TRUE))
  install.packages("here")
if (!requireNamespace("Matrix", quietly = TRUE))
  install.packages("Matrix")
if (!requireNamespace("DropletUtils", quietly = TRUE))
  BiocManager::install("DropletUtils")
if (!requireNamespace("MAST", quietly = TRUE))
  BiocManager::install("MAST")
if (!requireNamespace("SingleCellExperiment", quietly = TRUE))
  BiocManager::install("SingleCellExperiment")
if (!requireNamespace("scater", quietly = TRUE))
  BiocManager::install("scater")

print("All required packages installed!")
